version: '3.1'
services:
  postgres:
    image: 'postgres:alpine'
    container_name: 'docker-postgres-ujikom39'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'penjualan'
      POSTGRES_USER: 'rifuki'
      POSTGRES_PASSWORD: 'hontou?'
